# version: 0.2
# phases:
#   pre_build:
#     commands:
#       - echo Logging in to Amazon ECR...
#       - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
#       - IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Auto-incremented version tag
#       - echo $IMAGE_TAG
#   build:
#     commands:
#       - echo Building the Docker image...
#       - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
#       - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG 
#   post_build:
#     commands:
#       - echo Pushing the Docker image...
#       - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
#       - echo Writing image definitions...
#       - printf '[{"name":"todo-app-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
# artifacts:
#   files: imagedefinitions.json


# version: 0.2
# env:
#   variables:
#     AWS_ACCOUNT_ID: "965080479351"  # Replace with your AWS Account ID
#     AWS_DEFAULT_REGION: "ap-southeast-1"  # Replace with your desired region
#     IMAGE_REPO_NAME: "nodejs-todoapp"
#     ECS_CLUSTER: "todo-app-cluster"  # Add your ECS cluster name here if not provided in the CodeBuild environment settings.
#     SERVICE_NAME: "todo-app-service"  
# phases:
#   pre_build:
#     commands:
#       - echo Logging in to Amazon ECR...
#       - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
#       - IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Auto-incremented version tag
#       - echo $IMAGE_TAG
#   build:
#     commands:
#       - echo Building the Docker image...
#       - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
#       - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG 
#   post_build:
#     commands:
#       - echo Pushing the Docker image...
#       - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
#       - echo Writing image definitions...
#       - printf '[{"name":"todo-app-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
#       - echo Creating ECS Task Definition...
#       - >
#         TASK_DEFINITION=$(cat <<EOF
#         {
#           "family": "todo-app-task",
#           "containerDefinitions": [
#             {
#               "name": "todo-app-container",
#               "image": "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG",
#               "essential": true,
#               "memory": 128,  # Smallest possible memory size (MB)
#               "cpu": 128,     # Smallest possible CPU size (units)
#               "portMappings": [
#                 {
#                   "containerPort": 3000,
#                   "hostPort": 0,   # Auto-assign host port
#                   "protocol": "tcp"
#                 }
#               ]
#             }
#           ]
#         }
#         EOF
#         )
#       - echo Registering ECS Task Definition...
#       - echo $TASK_DEFINITION > task-definition.json
#       - aws ecs register-task-definition --cli-input-json file://task-definition.json

#       - echo Updating ECS Service with new task definition...
#       - NEW_TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition todo-app-task --query "taskDefinition.taskDefinitionArn" --output text)
#       - echo $NEW_TASK_DEF_ARN
#       - aws ecs update-service --cluster $ECS_CLUSTER --service $SERVICE_NAME --task-definition $NEW_TASK_DEF_ARN --force-new-deployment
    
# artifacts:
#   files:
#     - imagedefinitions.json
#     - task-definition.json


version: 0.2
env:
  variables:
    AWS_ACCOUNT_ID: "965080479351"
    AWS_DEFAULT_REGION: "ap-southeast-1"
    IMAGE_REPO_NAME: "nodejs-todoapp"
    ECS_CLUSTER: "my-cluster"
    SERVICE_NAME: "todo-app-service"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo $IMAGE_TAG
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image definitions...
      - printf '[{"name":"todo-app-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
      - echo Preparing task definition file...
      - cp task-definition.json task-definition-temp.json
      - sed -i "s|\$AWS_ACCOUNT_ID|$AWS_ACCOUNT_ID|g" task-definition-temp.json
      - sed -i "s|\$AWS_DEFAULT_REGION|$AWS_DEFAULT_REGION|g" task-definition-temp.json
      - sed -i "s|\$IMAGE_REPO_NAME|$IMAGE_REPO_NAME|g" task-definition-temp.json
      - sed -i "s|\$IMAGE_TAG|$IMAGE_TAG|g" task-definition-temp.json
      # Output the contents for debugging
      - echo "Contents of task-definition-temp.json:"
      - cat task-definition-temp.json
      - echo Registering ECS Task Definition...
      - aws ecs register-task-definition --cli-input-json file://task-definition-temp.json

      ####Update path#########
      # Get the latest task definition ARN dynamically
      - echo Fetching the latest task definition ARN...
      - LATEST_TASK_DEFINITION_ARN=$(aws ecs list-task-definitions --family-prefix $TASK_FAMILY --sort DESC --region $AWS_DEFAULT_REGION --query "taskDefinitionArns[0]" --output text)
      - echo "Latest Task Definition ARN: $LATEST_TASK_DEFINITION_ARN"

      # Update the ECS service with the latest task definition
      - echo Updating the ECS service with the latest task definition...
      - aws ecs update-service --cluster $ECS_CLUSTER --service $SERVICE_NAME --task-definition $LATEST_TASK_DEFINITION_ARN --region $AWS_DEFAULT_REGION

artifacts:
  files:
    - imagedefinitions.json
    - task-definition-temp.json

  # Uploading artifacts to S3
  base-directory: .  # Current directory (root of CodeBuild environment)
  discard-paths: yes
  s3:
    bucket: awscicddemohmp
    path: cawscicddemohmp/todo-app  # Directory inside your S3 bucket


# version: 0.2
# phases:
#   pre_build:
#     commands:
#       - echo Logging in to Amazon ECR...
#       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      
#       # Fetch the latest Git tag
#       - echo Fetching the latest Git tag...
#       - git fetch --tags
#       - CURRENT_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1) || echo "1.0")
#       - echo "Current Version: $CURRENT_VERSION"
      
#       # Increment the version
#       - MAJOR=$(echo $CURRENT_VERSION | cut -d'.' -f1)
#       - MINOR=$(echo $CURRENT_VERSION | cut -d'.' -f2)
#       - NEW_MINOR=$((MINOR + 1))
#       - NEW_VERSION="$MAJOR.$NEW_MINOR"
#       - echo "New Version: $NEW_VERSION"

#   build:
#     commands:
#       - echo Building Docker image with tag $NEW_VERSION...
#       - docker build -t $REPOSITORY_URI:$NEW_VERSION .

#   post_build:
#     commands:
#       - echo Tagging the new version in GitHub...
#       - git tag $NEW_VERSION
#       - git push origin $NEW_VERSION
      
#       - echo Pushing the Docker image to ECR...
#       - docker push $REPOSITORY_URI:$NEW_VERSION
